<?php

namespace Proxies\__CG__\Avalanche\Bundle\SitemapBundle\Sitemap;

use Doctrine\ODM\MongoDB\Persisters\DocumentPersister;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class Url extends \Avalanche\Bundle\SitemapBundle\Sitemap\Url implements \Doctrine\ODM\MongoDB\Proxy\Proxy
{
    private $__documentPersister__;
    public $__identifier__;
    public $__isInitialized__ = false;
    public function __construct(DocumentPersister $documentPersister, $identifier)
    {
        $this->__documentPersister__ = $documentPersister;
        $this->__identifier__ = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->__documentPersister__) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->__documentPersister__->load($this->__identifier__, $this) === null) {
                throw \Doctrine\ODM\MongoDB\DocumentNotFoundException::documentNotFound(get_class($this), $this->__identifier__);
            }
            unset($this->__documentPersister__, $this->__identifier__);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return $this->__identifier__;
        }
        $this->__load();
        return parent::getId();
    }

    public function getLoc()
    {
        $this->__load();
        return parent::getLoc();
    }

    public function setLastmod(\DateTime $lastmod)
    {
        $this->__load();
        return parent::setLastmod($lastmod);
    }

    public function getLastmod()
    {
        $this->__load();
        return parent::getLastmod();
    }

    public function setChangefreq($changefreq)
    {
        $this->__load();
        return parent::setChangefreq($changefreq);
    }

    public function getChangefreq()
    {
        $this->__load();
        return parent::getChangefreq();
    }

    public function setPriority($priority)
    {
        $this->__load();
        return parent::setPriority($priority);
    }

    public function getPriority()
    {
        $this->__load();
        return parent::getPriority();
    }

    public function add(\Avalanche\Bundle\SitemapBundle\Sitemap\Url\Image $image)
    {
        $this->__load();
        return parent::add($image);
    }

    public function remove(\Avalanche\Bundle\SitemapBundle\Sitemap\Url\Image $image)
    {
        $this->__load();
        return parent::remove($image);
    }

    public function all()
    {
        $this->__load();
        return parent::all();
    }

    public function clear()
    {
        $this->__load();
        return parent::clear();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'loc', 'lastmod', 'changefreq', 'priority', 'images');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->__documentPersister__) {
            $this->__isInitialized__ = true;
            $class = $this->__documentPersister__->getClassMetadata();
            $original = $this->__documentPersister__->load($this->__identifier__);
            if ($original === null) {
                throw \Doctrine\ODM\MongoDB\MongoDBException::documentNotFound(get_class($this), $this->__identifier__);
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->__documentPersister__, $this->__identifier__);
        }
        
    }
}