imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: en }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        path:     %database_path%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false
    
eyeswebcrea_referencement:
    rubriqueId: 1
    article_manager: spip_acces_content.article_manager
    routes-sitemap: ["SiteHomeBundle_homepage", "SiteHomeBundle_contact", "SiteHomeBundle_lacarte"] 
eyeswebcrea_alias_content_viewer:
    article_manager: spip_acces_content.article_manager
    rubrique_manager: ~
    
ihqs_contact:
    contact:
        form:
            type:               ihqs_contact_contact
            handler:            ihqs_contact.contact.form.handler.default
            name:               ihqs_contact_contact_form
            validation_groups:  [Contact]
    form: ~                                 # (optional) class managing the contact form
    model: ~                                # (optional) class managing the model
    connectors:                             # the list of "listeners" (or connectors here)
        email:                              # connecting the email listener
            recipients: jpasqualini@eyeswebcrea.fr    # giving him the recipient(s) email(s)
        database:                           # connecting the database listener
            db_driver: orm                  # giving him the database driver
        file: ~                             # connecting the file logger listener
    
avalanche_sitemap:
    base_url: "http://www.restaurantdiclarenzo.com/"
    database: restaurantdiclarenzo
    
google:
    analytics:
        trackers:
            default:
                name:      restaurantdiclarenzotracked
                accountId: UA-xxxx-x
                domain:    .restaurantdiclarenzo.com
                trackPageLoadTime: true


doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
            options:
                connect: true
    default_database: test_database
    document_managers:
        default:
            mappings:
            # other bundles mapping and etc.
                AvalancheSitemapBundle:
                    type: yml
                    prefix: Avalanche\Bundle\SitemapBundle\Sitemap
                    