<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class AvalancheBundleSitemapBundleSitemapUrlImageHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="string") */
        if (isset($data['loc'])) {
            $value = $data['loc'];
            $return = (string) $value;
            $this->class->reflFields['loc']->setValue($document, $return);
            $hydratedData['loc'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['caption'])) {
            $value = $data['caption'];
            $return = (string) $value;
            $this->class->reflFields['caption']->setValue($document, $return);
            $hydratedData['caption'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['geoLocation'])) {
            $value = $data['geoLocation'];
            $return = (string) $value;
            $this->class->reflFields['geoLocation']->setValue($document, $return);
            $hydratedData['geoLocation'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['title'])) {
            $value = $data['title'];
            $return = (string) $value;
            $this->class->reflFields['title']->setValue($document, $return);
            $hydratedData['title'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['license'])) {
            $value = $data['license'];
            $return = (string) $value;
            $this->class->reflFields['license']->setValue($document, $return);
            $hydratedData['license'] = $return;
        }
        return $hydratedData;
    }
}