<?php

namespace Proxies\__CG__\Avalanche\Bundle\SitemapBundle\Sitemap\Url;

use Doctrine\ODM\MongoDB\Persisters\DocumentPersister;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class Image extends \Avalanche\Bundle\SitemapBundle\Sitemap\Url\Image implements \Doctrine\ODM\MongoDB\Proxy\Proxy
{
    private $__documentPersister__;
    public $__identifier__;
    public $__isInitialized__ = false;
    public function __construct(DocumentPersister $documentPersister, $identifier)
    {
        $this->__documentPersister__ = $documentPersister;
        $this->__identifier__ = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->__documentPersister__) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->__documentPersister__->load($this->__identifier__, $this) === null) {
                throw \Doctrine\ODM\MongoDB\DocumentNotFoundException::documentNotFound(get_class($this), $this->__identifier__);
            }
            unset($this->__documentPersister__, $this->__identifier__);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getLoc()
    {
        $this->__load();
        return parent::getLoc();
    }

    public function setCaption($caption)
    {
        $this->__load();
        return parent::setCaption($caption);
    }

    public function getCaption()
    {
        $this->__load();
        return parent::getCaption();
    }

    public function setGeoLocation($geoLocation)
    {
        $this->__load();
        return parent::setGeoLocation($geoLocation);
    }

    public function getGeoLocation()
    {
        $this->__load();
        return parent::getGeoLocation();
    }

    public function setTitle($title)
    {
        $this->__load();
        return parent::setTitle($title);
    }

    public function getTitle()
    {
        $this->__load();
        return parent::getTitle();
    }

    public function setLicense($license)
    {
        $this->__load();
        return parent::setLicense($license);
    }

    public function getLicense()
    {
        $this->__load();
        return parent::getLicense();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'loc', 'caption', 'geoLocation', 'title', 'license');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->__documentPersister__) {
            $this->__isInitialized__ = true;
            $class = $this->__documentPersister__->getClassMetadata();
            $original = $this->__documentPersister__->load($this->__identifier__);
            if ($original === null) {
                throw \Doctrine\ODM\MongoDB\MongoDBException::documentNotFound(get_class($this), $this->__identifier__);
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->__documentPersister__, $this->__identifier__);
        }
        
    }
}