<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class SpipAccesContentBundleEntitySpipVersionsFragmentsProxy extends \Spip\AccesContentBundle\Entity\SpipVersionsFragments implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function setIdArticle($idArticle)
    {
        $this->__load();
        return parent::setIdArticle($idArticle);
    }

    public function getIdArticle()
    {
        $this->__load();
        return parent::getIdArticle();
    }

    public function setIdFragment($idFragment)
    {
        $this->__load();
        return parent::setIdFragment($idFragment);
    }

    public function getIdFragment()
    {
        $this->__load();
        return parent::getIdFragment();
    }

    public function setVersionMin($versionMin)
    {
        $this->__load();
        return parent::setVersionMin($versionMin);
    }

    public function getVersionMin()
    {
        $this->__load();
        return parent::getVersionMin();
    }

    public function setVersionMax($versionMax)
    {
        $this->__load();
        return parent::setVersionMax($versionMax);
    }

    public function getVersionMax()
    {
        $this->__load();
        return parent::getVersionMax();
    }

    public function setCompress($compress)
    {
        $this->__load();
        return parent::setCompress($compress);
    }

    public function getCompress()
    {
        $this->__load();
        return parent::getCompress();
    }

    public function setFragment($fragment)
    {
        $this->__load();
        return parent::setFragment($fragment);
    }

    public function getFragment()
    {
        $this->__load();
        return parent::getFragment();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idArticle', 'idFragment', 'versionMin', 'versionMax', 'compress', 'fragment');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}