<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class SpipAccesContentBundleEntitySpipAuteursProxy extends \Spip\AccesContentBundle\Entity\SpipAuteurs implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getIdAuteur()
    {
        $this->__load();
        return parent::getIdAuteur();
    }

    public function setNom($nom)
    {
        $this->__load();
        return parent::setNom($nom);
    }

    public function getNom()
    {
        $this->__load();
        return parent::getNom();
    }

    public function setBio($bio)
    {
        $this->__load();
        return parent::setBio($bio);
    }

    public function getBio()
    {
        $this->__load();
        return parent::getBio();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setNomSite($nomSite)
    {
        $this->__load();
        return parent::setNomSite($nomSite);
    }

    public function getNomSite()
    {
        $this->__load();
        return parent::getNomSite();
    }

    public function setUrlSite($urlSite)
    {
        $this->__load();
        return parent::setUrlSite($urlSite);
    }

    public function getUrlSite()
    {
        $this->__load();
        return parent::getUrlSite();
    }

    public function setLogin($login)
    {
        $this->__load();
        return parent::setLogin($login);
    }

    public function getLogin()
    {
        $this->__load();
        return parent::getLogin();
    }

    public function setPass($pass)
    {
        $this->__load();
        return parent::setPass($pass);
    }

    public function getPass()
    {
        $this->__load();
        return parent::getPass();
    }

    public function setLowSec($lowSec)
    {
        $this->__load();
        return parent::setLowSec($lowSec);
    }

    public function getLowSec()
    {
        $this->__load();
        return parent::getLowSec();
    }

    public function setStatut($statut)
    {
        $this->__load();
        return parent::setStatut($statut);
    }

    public function getStatut()
    {
        $this->__load();
        return parent::getStatut();
    }

    public function setWebmestre($webmestre)
    {
        $this->__load();
        return parent::setWebmestre($webmestre);
    }

    public function getWebmestre()
    {
        $this->__load();
        return parent::getWebmestre();
    }

    public function setMaj($maj)
    {
        $this->__load();
        return parent::setMaj($maj);
    }

    public function getMaj()
    {
        $this->__load();
        return parent::getMaj();
    }

    public function setPgp($pgp)
    {
        $this->__load();
        return parent::setPgp($pgp);
    }

    public function getPgp()
    {
        $this->__load();
        return parent::getPgp();
    }

    public function setHtpass($htpass)
    {
        $this->__load();
        return parent::setHtpass($htpass);
    }

    public function getHtpass()
    {
        $this->__load();
        return parent::getHtpass();
    }

    public function setEnLigne($enLigne)
    {
        $this->__load();
        return parent::setEnLigne($enLigne);
    }

    public function getEnLigne()
    {
        $this->__load();
        return parent::getEnLigne();
    }

    public function setImessage($imessage)
    {
        $this->__load();
        return parent::setImessage($imessage);
    }

    public function getImessage()
    {
        $this->__load();
        return parent::getImessage();
    }

    public function setMessagerie($messagerie)
    {
        $this->__load();
        return parent::setMessagerie($messagerie);
    }

    public function getMessagerie()
    {
        $this->__load();
        return parent::getMessagerie();
    }

    public function setAleaActuel($aleaActuel)
    {
        $this->__load();
        return parent::setAleaActuel($aleaActuel);
    }

    public function getAleaActuel()
    {
        $this->__load();
        return parent::getAleaActuel();
    }

    public function setAleaFutur($aleaFutur)
    {
        $this->__load();
        return parent::setAleaFutur($aleaFutur);
    }

    public function getAleaFutur()
    {
        $this->__load();
        return parent::getAleaFutur();
    }

    public function setPrefs($prefs)
    {
        $this->__load();
        return parent::setPrefs($prefs);
    }

    public function getPrefs()
    {
        $this->__load();
        return parent::getPrefs();
    }

    public function setCookieOubli($cookieOubli)
    {
        $this->__load();
        return parent::setCookieOubli($cookieOubli);
    }

    public function getCookieOubli()
    {
        $this->__load();
        return parent::getCookieOubli();
    }

    public function setSource($source)
    {
        $this->__load();
        return parent::setSource($source);
    }

    public function getSource()
    {
        $this->__load();
        return parent::getSource();
    }

    public function setLang($lang)
    {
        $this->__load();
        return parent::setLang($lang);
    }

    public function getLang()
    {
        $this->__load();
        return parent::getLang();
    }

    public function setExtra($extra)
    {
        $this->__load();
        return parent::setExtra($extra);
    }

    public function getExtra()
    {
        $this->__load();
        return parent::getExtra();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idAuteur', 'nom', 'bio', 'email', 'nomSite', 'urlSite', 'login', 'pass', 'lowSec', 'statut', 'webmestre', 'maj', 'pgp', 'htpass', 'enLigne', 'imessage', 'messagerie', 'aleaActuel', 'aleaFutur', 'prefs', 'cookieOubli', 'source', 'lang', 'extra');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}