<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class SpipAccesContentBundleEntitySpipVersionsProxy extends \Spip\AccesContentBundle\Entity\SpipVersions implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function setIdArticle($idArticle)
    {
        $this->__load();
        return parent::setIdArticle($idArticle);
    }

    public function getIdArticle()
    {
        $this->__load();
        return parent::getIdArticle();
    }

    public function setIdVersion($idVersion)
    {
        $this->__load();
        return parent::setIdVersion($idVersion);
    }

    public function getIdVersion()
    {
        $this->__load();
        return parent::getIdVersion();
    }

    public function setDate($date)
    {
        $this->__load();
        return parent::setDate($date);
    }

    public function getDate()
    {
        $this->__load();
        return parent::getDate();
    }

    public function setIdAuteur($idAuteur)
    {
        $this->__load();
        return parent::setIdAuteur($idAuteur);
    }

    public function getIdAuteur()
    {
        $this->__load();
        return parent::getIdAuteur();
    }

    public function setTitreVersion($titreVersion)
    {
        $this->__load();
        return parent::setTitreVersion($titreVersion);
    }

    public function getTitreVersion()
    {
        $this->__load();
        return parent::getTitreVersion();
    }

    public function setPermanent($permanent)
    {
        $this->__load();
        return parent::setPermanent($permanent);
    }

    public function getPermanent()
    {
        $this->__load();
        return parent::getPermanent();
    }

    public function setChamps($champs)
    {
        $this->__load();
        return parent::setChamps($champs);
    }

    public function getChamps()
    {
        $this->__load();
        return parent::getChamps();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idArticle', 'idVersion', 'date', 'idAuteur', 'titreVersion', 'permanent', 'champs');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}