<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class SpipAccesContentBundleEntitySpipSignaturesProxy extends \Spip\AccesContentBundle\Entity\SpipSignatures implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getIdSignature()
    {
        $this->__load();
        return parent::getIdSignature();
    }

    public function setIdArticle($idArticle)
    {
        $this->__load();
        return parent::setIdArticle($idArticle);
    }

    public function getIdArticle()
    {
        $this->__load();
        return parent::getIdArticle();
    }

    public function setDateTime($dateTime)
    {
        $this->__load();
        return parent::setDateTime($dateTime);
    }

    public function getDateTime()
    {
        $this->__load();
        return parent::getDateTime();
    }

    public function setNomEmail($nomEmail)
    {
        $this->__load();
        return parent::setNomEmail($nomEmail);
    }

    public function getNomEmail()
    {
        $this->__load();
        return parent::getNomEmail();
    }

    public function setAdEmail($adEmail)
    {
        $this->__load();
        return parent::setAdEmail($adEmail);
    }

    public function getAdEmail()
    {
        $this->__load();
        return parent::getAdEmail();
    }

    public function setNomSite($nomSite)
    {
        $this->__load();
        return parent::setNomSite($nomSite);
    }

    public function getNomSite()
    {
        $this->__load();
        return parent::getNomSite();
    }

    public function setUrlSite($urlSite)
    {
        $this->__load();
        return parent::setUrlSite($urlSite);
    }

    public function getUrlSite()
    {
        $this->__load();
        return parent::getUrlSite();
    }

    public function setMessage($message)
    {
        $this->__load();
        return parent::setMessage($message);
    }

    public function getMessage()
    {
        $this->__load();
        return parent::getMessage();
    }

    public function setStatut($statut)
    {
        $this->__load();
        return parent::setStatut($statut);
    }

    public function getStatut()
    {
        $this->__load();
        return parent::getStatut();
    }

    public function setMaj($maj)
    {
        $this->__load();
        return parent::setMaj($maj);
    }

    public function getMaj()
    {
        $this->__load();
        return parent::getMaj();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idSignature', 'idArticle', 'dateTime', 'nomEmail', 'adEmail', 'nomSite', 'urlSite', 'message', 'statut', 'maj');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}