<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class SpipAccesContentBundleEntitySpipArticlesProxy extends \Spip\AccesContentBundle\Entity\SpipArticles implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getMots()
    {
        $this->__load();
        return parent::getMots();
    }

    public function isContainIdMot($id_mot)
    {
        $this->__load();
        return parent::isContainIdMot($id_mot);
    }

    public function isContainMot()
    {
        $this->__load();
        return parent::isContainMot();
    }

    public function addMot(\Spip\AccesContentBundle\Entity\SpipMots $mot)
    {
        $this->__load();
        return parent::addMot($mot);
    }

    public function getIdArticle()
    {
        $this->__load();
        return parent::getIdArticle();
    }

    public function setSurtitre($surtitre)
    {
        $this->__load();
        return parent::setSurtitre($surtitre);
    }

    public function getSurtitre()
    {
        $this->__load();
        return parent::getSurtitre();
    }

    public function setTitre($titre)
    {
        $this->__load();
        return parent::setTitre($titre);
    }

    public function getTitre()
    {
        $this->__load();
        return parent::getTitre();
    }

    public function getFullTitre()
    {
        $this->__load();
        return parent::getFullTitre();
    }

    public function getOrder()
    {
        $this->__load();
        return parent::getOrder();
    }

    public function setSoustitre($soustitre)
    {
        $this->__load();
        return parent::setSoustitre($soustitre);
    }

    public function getSoustitre()
    {
        $this->__load();
        return parent::getSoustitre();
    }

    public function setIdRubrique($idRubrique)
    {
        $this->__load();
        return parent::setIdRubrique($idRubrique);
    }

    public function getIdRubrique()
    {
        $this->__load();
        return parent::getIdRubrique();
    }

    public function setDescriptif($descriptif)
    {
        $this->__load();
        return parent::setDescriptif($descriptif);
    }

    public function getDescriptif()
    {
        $this->__load();
        return parent::getDescriptif();
    }

    public function setChapo($chapo)
    {
        $this->__load();
        return parent::setChapo($chapo);
    }

    public function getChapo()
    {
        $this->__load();
        return parent::getChapo();
    }

    public function setTexte($texte)
    {
        $this->__load();
        return parent::setTexte($texte);
    }

    public function getTexte()
    {
        $this->__load();
        return parent::getTexte();
    }

    public function isImageAvailable()
    {
        $this->__load();
        return parent::isImageAvailable();
    }

    public function setPs($ps)
    {
        $this->__load();
        return parent::setPs($ps);
    }

    public function getPs()
    {
        $this->__load();
        return parent::getPs();
    }

    public function setDate($date)
    {
        $this->__load();
        return parent::setDate($date);
    }

    public function getDate()
    {
        $this->__load();
        return parent::getDate();
    }

    public function setStatut($statut)
    {
        $this->__load();
        return parent::setStatut($statut);
    }

    public function getStatut()
    {
        $this->__load();
        return parent::getStatut();
    }

    public function setIdSecteur($idSecteur)
    {
        $this->__load();
        return parent::setIdSecteur($idSecteur);
    }

    public function getIdSecteur()
    {
        $this->__load();
        return parent::getIdSecteur();
    }

    public function setMaj($maj)
    {
        $this->__load();
        return parent::setMaj($maj);
    }

    public function getMaj()
    {
        $this->__load();
        return parent::getMaj();
    }

    public function setExport($export)
    {
        $this->__load();
        return parent::setExport($export);
    }

    public function getExport()
    {
        $this->__load();
        return parent::getExport();
    }

    public function setDateRedac($dateRedac)
    {
        $this->__load();
        return parent::setDateRedac($dateRedac);
    }

    public function getDateRedac()
    {
        $this->__load();
        return parent::getDateRedac();
    }

    public function setVisites($visites)
    {
        $this->__load();
        return parent::setVisites($visites);
    }

    public function getVisites()
    {
        $this->__load();
        return parent::getVisites();
    }

    public function setReferers($referers)
    {
        $this->__load();
        return parent::setReferers($referers);
    }

    public function getReferers()
    {
        $this->__load();
        return parent::getReferers();
    }

    public function setPopularite($popularite)
    {
        $this->__load();
        return parent::setPopularite($popularite);
    }

    public function getPopularite()
    {
        $this->__load();
        return parent::getPopularite();
    }

    public function setAccepterForum($accepterForum)
    {
        $this->__load();
        return parent::setAccepterForum($accepterForum);
    }

    public function getAccepterForum()
    {
        $this->__load();
        return parent::getAccepterForum();
    }

    public function setDateModif($dateModif)
    {
        $this->__load();
        return parent::setDateModif($dateModif);
    }

    public function getDateModif()
    {
        $this->__load();
        return parent::getDateModif();
    }

    public function setLang($lang)
    {
        $this->__load();
        return parent::setLang($lang);
    }

    public function getLang()
    {
        $this->__load();
        return parent::getLang();
    }

    public function getpathWebLogo()
    {
        $this->__load();
        return parent::getpathWebLogo();
    }

    public function getPathAbsoluteLocalLogo()
    {
        $this->__load();
        return parent::getPathAbsoluteLocalLogo();
    }

    public function getPathLocalLogo()
    {
        $this->__load();
        return parent::getPathLocalLogo();
    }

    public function setLangueChoisie($langueChoisie)
    {
        $this->__load();
        return parent::setLangueChoisie($langueChoisie);
    }

    public function getLangueChoisie()
    {
        $this->__load();
        return parent::getLangueChoisie();
    }

    public function setIdTrad($idTrad)
    {
        $this->__load();
        return parent::setIdTrad($idTrad);
    }

    public function getIdTrad()
    {
        $this->__load();
        return parent::getIdTrad();
    }

    public function setExtra($extra)
    {
        $this->__load();
        return parent::setExtra($extra);
    }

    public function getExtra()
    {
        $this->__load();
        return parent::getExtra();
    }

    public function setIdVersion($idVersion)
    {
        $this->__load();
        return parent::setIdVersion($idVersion);
    }

    public function getIdVersion()
    {
        $this->__load();
        return parent::getIdVersion();
    }

    public function setNomSite($nomSite)
    {
        $this->__load();
        return parent::setNomSite($nomSite);
    }

    public function getNomSite()
    {
        $this->__load();
        return parent::getNomSite();
    }

    public function setUrlSite($urlSite)
    {
        $this->__load();
        return parent::setUrlSite($urlSite);
    }

    public function getUrlSite()
    {
        $this->__load();
        return parent::getUrlSite();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'mots', 'idArticle', 'surtitre', 'titre', 'soustitre', 'idRubrique', 'descriptif', 'chapo', 'texte', 'ps', 'date', 'statut', 'idSecteur', 'maj', 'export', 'dateRedac', 'visites', 'referers', 'popularite', 'accepterForum', 'dateModif', 'lang', 'langueChoisie', 'idTrad', 'extra', 'idVersion', 'nomSite', 'urlSite');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}