<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class SpipAccesContentBundleEntitySpipAuteursMessagesProxy extends \Spip\AccesContentBundle\Entity\SpipAuteursMessages implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function setIdAuteur($idAuteur)
    {
        $this->__load();
        return parent::setIdAuteur($idAuteur);
    }

    public function getIdAuteur()
    {
        $this->__load();
        return parent::getIdAuteur();
    }

    public function setIdMessage($idMessage)
    {
        $this->__load();
        return parent::setIdMessage($idMessage);
    }

    public function getIdMessage()
    {
        $this->__load();
        return parent::getIdMessage();
    }

    public function setVu($vu)
    {
        $this->__load();
        return parent::setVu($vu);
    }

    public function getVu()
    {
        $this->__load();
        return parent::getVu();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idAuteur', 'idMessage', 'vu');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}